define({
  root: ({
    _widgetLabel: "Integrated Edit Widget",
    title: "Select a template to create features",
    pressStr: "Press ",
    ctrlStr: " CTRL ",
    snapStr: " to enable snapping",
    emptyGeocoderResponse: "The location of the feature you are interested in could not be found.Please use the Search Tool and/or the Map Tools to navigate to your location of interest.",
    multipleGeocoderResponse:"Multiple addresses matched the location you are trying to find.Please use the Search Tool to narrow down your search and/or use the Map Tools to navigate to your location of interest.",
    noFallbackAddressConfigured: "No fallback address configured in the URL.",
    ok: "OK",
    editScaleLimit: "Current scale limit is set to :",
    overrideScale: "Override?"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});